export const FETCH_USER_LOGIN_SUCCES = 'FETCH_USER_LOGIN_SUCCES';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_ALL_YACHT = 'GET_ALL_YACHT';
export const GET_YACHT_BY_ID = 'GET_YACHT_BY_ID';
export const GET_YACHT_IMAGE = 'GET_YACHT_IMAGE';
export const GET_ALL_SERVICE = 'GET_ALL_SERVICE';
export const GET_SERVICE_BY_YACHT = 'GET_SERVICE_BY_YACHT';


//loginAdmin type
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMER';
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';

export const CREATE_COMPANY_ACCOUNT = 'CREATE_COMPANY_ACCOUNT';
export const ADD_COMPANY_INFO = 'ADD_COMPANY_INFO';
export const GET_SCHEDULE_BY_YACHT = 'GET_SCHEDULE_BY_YACHT';
export const ADD_ROOM = 'ADD_ROOM';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const RESET_SELECTION = 'RESET_SELECTION'
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE'
export const GET_ALL_ROOM_TYPE = 'GET_ALL_ROOM_TYPE';
export const GET_ROOM_IMAGES = 'GET_ROOM_IMAGES'
export const INFORMATION_CUSTOMER = 'INFORMATION_CUSTOMER';
export const CUSTOMER_REGISTER = 'CUSTOMER_REGISTER';
export const SEARCH_YACHT = 'SEARCH_YACHT';
export const GET_ALL_ROOM_BY_YACHT = 'GET_ALL_ROOM_BY_YACHT';
export const FILTER_YACHT = 'FILTER_YACHT'
export const GET_ALL_YACHT_TYPE = 'GET_ALL_YACHT_TYPE'
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const BOOK_WHOLE_YACHT = 'BOOK_WHOLE_YACHT'
export const HANDLE_SERVICE_CHANGE = 'HANDLE_SERVICE_CHANGE';
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE';
export const CLEAR_SELECTION_WHEN_EXIT = 'CLEAR_SELECTION_WHEN_EXIT';
export const GET_SCHEDULE_BY_ID = 'GET_SCHEDULE_BY_ID';
