export const FETCH_USER_LOGIN_SUCCES = 'FETCH_USER_LOGIN_SUCCES';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_ALL_YACHT = 'GET_ALL_YACHT';
export const GET_YACHT_BY_ID = 'GET_YACHT_BY_ID';
export const GET_YACHT_IMAGE = 'GET_YACHT_IMAGE';
export const GET_ALL_SERVICE = 'GET_ALL_SERVICE';
export const GET_SERVICE_BY_YACHT = 'GET_SERVICE_BY_YACHT';
export const GET_SCHEDULE_BY_YACHT = 'GET_SCHEDULE_BY_YACHT';