name: Build and deploy Node.js app to Azure Web App - testBookingYacht CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bookingyacht  # Adjust this if the directory is different

    steps:
      - uses: actions/checkout@v4

      - name: Display directory structure
        run: ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Check if release.zip exists
        run: ls -la release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Confirm artifact upload
        run: echo "Artifact uploaded"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    defaults:
      run:
        working-directory: bookingyacht  # Adjust this if the directory is different

    steps:
      - name: List artifacts available for download (debugging)
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | {name, url}'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Check artifact contents
        run: unzip -l release.zip

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deployment

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "testBookingYacht"
          slot-name: "Production"
          package: deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2D7847427A34165B0A257915AF159DB }}
